spring:
  datasource:
    password: 12345
    username: root
    url: jdbc:mysql://localhost:3306/testjwt_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: 2948404D635166546A576E5A7234753778214125442A462D4A614E645267556B
