spring:
  datasource:
    username: root
    password: 91170151
    url: jdbc:mysql://localhost:3306/db_soapa?createDatabaseIfNotExist=true
    drive-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true