spring:
  datasource:
    password: 12345
    username: root
    url: jdbc:mysql://localhost:3306/textjwt2_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: f8460fcd-42e3-4bfd-a6c6-c07023625bd7


